import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { VapiProvider } from "./VapiProvider";
import { headers } from 'next/headers';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Force dynamic rendering to avoid hydration mismatch
  headers();
  
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <VapiProvider>{children}</VapiProvider>
      </body>
    </html>
  );
}
